"""initial schema

Revision ID: 94f76054fb54
Revises: 
Create Date: 2026-07-10 04:11:47.721786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94f76054fb54'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('pages_fetched', sa.Integer(), nullable=False),
    sa.Column('items_saved', sa.Integer(), nullable=False),
    sa.Column('items_duplicate', sa.Integer(), nullable=False),
    sa.Column('escalations', sa.Integer(), nullable=False),
    sa.Column('errors', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('every_hours', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interview_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('round', sa.String(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=False),
    sa.Column('question_hash', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('extraction_tier', sa.String(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_hash')
    )
    op.create_index(op.f('ix_interview_questions_source_url'), 'interview_questions', ['source_url'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('company', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('salary', sa.String(), nullable=True),
    sa.Column('requirements', sa.JSON(), nullable=False),
    sa.Column('posting_url', sa.String(), nullable=False),
    sa.Column('apply_url', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('extraction_tier', sa.String(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('starred', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('posting_url')
    )
    # ### end Alembic commands ###

    # Hand-added, not autogenerated: vec0 (phase 6 step 7) and FTS5 (phase 6
    # step 8) are raw SQLite virtual tables outside Base.metadata on purpose
    # (DESIGN.md §3, backend/db/vectors.py & fts.py) — autogenerate has no
    # visibility into them (confirmed for real while drafting this migration:
    # run against a DB that already had them, it misidentified their own
    # internal shadow tables as "removed"). 768 mirrors config.EMBED_DIM as
    # of this migration; frozen here on purpose — a real dimension change
    # is itself a future migration, not a moving reference to app code.
    op.execute(
        "CREATE VIRTUAL TABLE IF NOT EXISTS job_embeddings USING vec0(embedding float[768])"
    )
    op.execute(
        "CREATE VIRTUAL TABLE IF NOT EXISTS question_embeddings USING vec0(embedding float[768])"
    )
    op.execute(
        "CREATE VIRTUAL TABLE IF NOT EXISTS job_search_fts "
        "USING fts5(title, company, location, salary, requirements)"
    )
    op.execute(
        "CREATE VIRTUAL TABLE IF NOT EXISTS question_search_fts "
        "USING fts5(question, company, role)"
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP TABLE IF EXISTS question_search_fts")
    op.execute("DROP TABLE IF EXISTS job_search_fts")
    op.execute("DROP TABLE IF EXISTS question_embeddings")
    op.execute("DROP TABLE IF EXISTS job_embeddings")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobs')
    op.drop_index(op.f('ix_interview_questions_source_url'), table_name='interview_questions')
    op.drop_table('interview_questions')
    op.drop_table('schedules')
    op.drop_table('runs')
    # ### end Alembic commands ###
